version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 17985412
      MYSQL_DATABASE: stage_upgrade
      MYSQL_USER: stage_upgrade
      MYSQL_PASSWORD: password

  backend:
    build: .
    depends_on:
      - mariadb
    ports:
      - 5000:5000
      - 9229:9229  # debugger port
    volumes:
      - .:/usr/src/app
      - /usr/src/app/.pnpm-store
      - /usr/src/app/node_modules
    command: pnpm start:docker
    environment:
      DATABASE_URL: mysql://stage_upgrade:password@mariadb:3306/stage_upgrade
      PORT: 5000
